package pojo;
// Generated Mar 18, 2015 12:18:02 AM by Hibernate Tools 4.3.1



/**
 * AssistancequeueId generated by hbm2java
 */
public class AssistancequeueId  implements java.io.Serializable {


     private int labId;
     private int traineeId;

    public AssistancequeueId() {
    }

    public AssistancequeueId(int labId, int traineeId) {
       this.labId = labId;
       this.traineeId = traineeId;
    }
   
    public int getLabId() {
        return this.labId;
    }
    
    public void setLabId(int labId) {
        this.labId = labId;
    }
    public int getTraineeId() {
        return this.traineeId;
    }
    
    public void setTraineeId(int traineeId) {
        this.traineeId = traineeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AssistancequeueId) ) return false;
		 AssistancequeueId castOther = ( AssistancequeueId ) other; 
         
		 return (this.getLabId()==castOther.getLabId())
 && (this.getTraineeId()==castOther.getTraineeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLabId();
         result = 37 * result + this.getTraineeId();
         return result;
   }   


}


