package pojo;
// Generated Mar 20, 2015 2:19:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Deliveryqueue generated by hbm2java
 */
public class Deliveryqueue  implements java.io.Serializable, Comparable {


     private Lab lab;
     private Trainee trainee;
     private Date requestDate;
     private Boolean activated;

    public Deliveryqueue() {
    }

    public Lab getLab() {
        return this.lab;
    }
    
    public void setLab(Lab lab) {
        this.lab = lab;
    }
    public Trainee getTrainee() {
        return this.trainee;
    }
    
    public void setTrainee(Trainee trainee) {
        this.trainee = trainee;
    }
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
    public Boolean getActivated() {
        return this.activated;
    }
    
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Deliveryqueue)) return false;

        Deliveryqueue that = (Deliveryqueue) o;

        if (!lab.equals(that.lab)) return false;
        if (!trainee.equals(that.trainee)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = lab.hashCode();
        result = 31 * result + trainee.hashCode();
        return result;
    }


    @Override
    public int compareTo(Object o) {
        return ((Deliveryqueue)o).requestDate.compareTo(this.requestDate);
    }
}


