package pojo;
// Generated Mar 20, 2015 2:19:00 PM by Hibernate Tools 4.3.1



/**
 * DeliveryqueueId generated by hbm2java
 */
public class DeliveryqueueId  implements java.io.Serializable {


     private Long labId;
     private Long traineeId;

    public DeliveryqueueId() {
    }

    public DeliveryqueueId(Long labId, Long traineeId) {
       this.labId = labId;
       this.traineeId = traineeId;
    }
   
    public Long getLabId() {
        return this.labId;
    }
    
    public void setLabId(Long labId) {
        this.labId = labId;
    }
    public Long getTraineeId() {
        return this.traineeId;
    }
    
    public void setTraineeId(Long traineeId) {
        this.traineeId = traineeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeliveryqueueId) ) return false;
		 DeliveryqueueId castOther = ( DeliveryqueueId ) other; 
         
		 return (this.getLabId()==castOther.getLabId())
 && (this.getTraineeId()==castOther.getTraineeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = (int) (37 * result + this.getLabId());
         result = (int) (37 * result + this.getTraineeId());
         return result;
   }   


}


