package pojo;
// Generated Mar 20, 2015 2:19:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Lab generated by hbm2java
 */
public class Lab  implements java.io.Serializable {


     private Long id;
     private Course course;
     private String name;
     private String startTimeQueues;
     private String endTimeQueues;
     private String startTimeFileUpload;
     private String endTimeFileUpload;
     private Boolean activated;
     private Set deliveryqueues = new HashSet(0);
     private Set assignments = new HashSet(0);
     private Set instructors = new HashSet(0);
     private Set assistancequeues = new HashSet(0);

    public Lab() {
    }

    public Lab(Course course, String name, String startTimeQueues, String endTimeQueues, String startTimeFileUpload, String endTimeFileUpload, Boolean activated, Set deliveryqueues, Set assignments, Set instructors, Set assistancequeues) {
       this.course = course;
       this.name = name;
       this.startTimeQueues = startTimeQueues;
       this.endTimeQueues = endTimeQueues;
       this.startTimeFileUpload = startTimeFileUpload;
       this.endTimeFileUpload = endTimeFileUpload;
       this.activated = activated;
       this.deliveryqueues = deliveryqueues;
       this.assignments = assignments;
       this.instructors = instructors;
       this.assistancequeues = assistancequeues;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStartTimeQueues() {
        return this.startTimeQueues;
    }
    
    public void setStartTimeQueues(String startTimeQueues) {
        this.startTimeQueues = startTimeQueues;
    }
    public String getEndTimeQueues() {
        return this.endTimeQueues;
    }
    
    public void setEndTimeQueues(String endTimeQueues) {
        this.endTimeQueues = endTimeQueues;
    }
    public String getStartTimeFileUpload() {
        return this.startTimeFileUpload;
    }
    
    public void setStartTimeFileUpload(String startTimeFileUpload) {
        this.startTimeFileUpload = startTimeFileUpload;
    }
    public String getEndTimeFileUpload() {
        return this.endTimeFileUpload;
    }
    
    public void setEndTimeFileUpload(String endTimeFileUpload) {
        this.endTimeFileUpload = endTimeFileUpload;
    }
    public Boolean getActivated() {
        return this.activated;
    }
    
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }
    public Set getDeliveryqueues() {
        return this.deliveryqueues;
    }
    
    public void setDeliveryqueues(Set deliveryqueues) {
        this.deliveryqueues = deliveryqueues;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }
    public Set getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set instructors) {
        this.instructors = instructors;
    }
    public Set getAssistancequeues() {
        return this.assistancequeues;
    }
    
    public void setAssistancequeues(Set assistancequeues) {
        this.assistancequeues = assistancequeues;
    }




}


