package pojo;
// Generated Mar 18, 2015 12:18:02 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trainee generated by hbm2java
 */
public class Trainee  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private String email;
     private Boolean activated;
     private Set assistancequeues = new HashSet(0);
     private Set assignments = new HashSet(0);
     private Set deliveryqueues = new HashSet(0);
     private Set groups = new HashSet(0);

    public Trainee() {
    }

    public Trainee(String username, String password, String email, Boolean activated, Set assistancequeues, Set assignments, Set deliveryqueues, Set groups) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.activated = activated;
       this.assistancequeues = assistancequeues;
       this.assignments = assignments;
       this.deliveryqueues = deliveryqueues;
       this.groups = groups;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getActivated() {
        return this.activated;
    }
    
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }
    public Set getAssistancequeues() {
        return this.assistancequeues;
    }
    
    public void setAssistancequeues(Set assistancequeues) {
        this.assistancequeues = assistancequeues;
    }
    public Set getAssignments() {
        return this.assignments;
    }
    
    public void setAssignments(Set assignments) {
        this.assignments = assignments;
    }
    public Set getDeliveryqueues() {
        return this.deliveryqueues;
    }
    
    public void setDeliveryqueues(Set deliveryqueues) {
        this.deliveryqueues = deliveryqueues;
    }
    public Set getGroups() {
        return this.groups;
    }
    
    public void setGroups(Set groups) {
        this.groups = groups;
    }




}


